# Generated by Django 5.0.1 on 2025-06-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('edit', 'Edit'), ('calculate_interest', 'Calculate Interest'), ('release', 'Release')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serial_number', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in grams', max_digits=10)),
                ('customer_name', models.CharField(max_length=100)),
                ('given_by', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('removed', 'Removed')], default='active', max_length=10)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('interest_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
