# Generated by Django 5.0.1 on 2025-06-10 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='entry',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
